name: go-app

cpu: 250m
memory: 256Mi
replicas: 2
maxSurge: 25%
maxUnavailable: 25%
deploymentStrategy: RollingUpdate
image:
  tag: "tag"


service:
  type: LoadBalancer
  port: 
    targetPort: 8000
    protocol: TCP


toleration: taint-test