on: push

name: CI-CD

jobs:
  ci:
    runs-on: ubuntu-latest
    uses: sincros121/y2_devosp_test_templates/.github/workflows/ci.yaml@main
    secrets: inherit
    with:
      service_name: go-app
      dockerfile_path: "."
      context_path: "."

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    uses: sincros121/y2_devosp_test_templates/.github/workflows/cd.yaml@main
    secrets: inherit